### ISSUE TITLE
Missing Dependency in `PluginAutomaticTestBuilder`?

### ISSUE THREAD

**Issue by sghill** [jenkinsci/jenkins-test-harness#655] opened 2023-09-17 00:45 UTC
Hi,

I'm not quite sure where to report this issue, but this seems like a reasonable place to start. The answer may well end up being somewhere else, however - I also faced this issue when updating plugins on my most recent Jenkins deployment. Declaring the commons-text-api as a top-level dependency worked there, which points to this being more than a test harness issue.

I've been updating some plugins from baseline Jenkins 2.375.4 to 2.387.3 and getting several failures from `InjectedTest.testPluginActive` that look like this:

```
[ERROR] InjectedTest.testPluginActive -- Time elapsed: 0.003 s <<< FAILURE!
java.lang.AssertionError: While testing build-name-setter, plugin-util-api failed to start
        at org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive(PluginAutomaticTestBuilder.java:98)
...
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Failed to load: Plugin Utilities API Plugin (plugin-util-api 3.3.0)
 - Plugin is missing: commons-text-api (1.10.0-36.vc008c8fcda_7b_)
 - Plugin is missing: commons-lang3-api (3.12.0-36.vd97de6465d5b_)
```

`plugin-util-api` is not a dependency of the project. In looking at the dependencies of recent releases of plugin-util-api, I did not see anything to suggest this dependency was just dropped either. Here are a few examples where running `mvn clean verify` will reproduce the problem:

* https://github.com/sghill-rewrite/build-name-setter-plugin/commit/37109a998d18f6f203c3652c23581922c48484e2
* https://github.com/sghill-rewrite/description-setter-plugin/commit/318c11746c799a55f20ee738b5f0d3d811cda0ae
* https://github.com/sghill-rewrite/matrix-project-plugin/commit/45b8215849a8a47e680a668195ae1e1f6465a81c
* https://github.com/sghill-rewrite/plugin-usage-plugin/commit/70c7f3c7893354706ad0c0c6d005c8bc78003cc7
* https://github.com/sghill-rewrite/project-stats-plugin/commit/5de167e838072542fb4efaaba73b7577fac91ec2

In one case I fixed the test by adding a test-scoped dependency, but a more centralized fix would be better.
https://github.com/jenkinsci/naginator-plugin/commit/85c11e2db507cc3380d376de5b0fcfc268fbc1bd

**Comment by jonesbusy** [comment] 2023-09-17 05:34
Was initially reported on BOM: https://github.com/jenkinsci/bom/issues/2484 but the culprit is checks-api-plugin

**Comment by MarkEWaite** [comment] 2023-09-17 07:50
> Was initially reported on BOM: [jenkinsci/bom#2484](https://github.com/jenkinsci/bom/issues/2484) but the culprit is checks-api-plugin

We hope to remove the requirement for that workaround in the next plugin BOM release, expected within the next day or two.

**Comment by MarkEWaite** [comment] 2023-09-17 07:52
Closing this issue because the root cause issue is tracked in the checks-api plugin as:

* https://github.com/jenkinsci/checks-api-plugin/issues/233

Thanks for reporting the issue @sghill !

**Closed by MarkEWaite** 2023-09-17 07:52 UTC
